name: Build & release Docker image

on:
  push:
    branches: [main]        # run after code is merged to main

# ──────────────────────────────────────────────────────────────
# Permissions needed for keyless signing
# ──────────────────────────────────────────────────────────────
permissions:
  contents: write           # required to create release
  id-token: write           # enable GitHub OIDC for cosign

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: polarity-slack-bot

    steps:
      - uses: actions/checkout@v4

      # ──────────────────────────────────────────────────────────────
      # 1. Node 24 environment & install deps
      # ──────────────────────────────────────────────────────────────
      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci --omit=optional

      # ──────────────────────────────────────────────────────────────
      # 2. Extract package.json version
      # ──────────────────────────────────────────────────────────────
      - name: Extract package version
        id: pkg
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Prepare env
        run: |
          echo "IMAGE_TAG=${{ steps.pkg.outputs.version }}" >> $GITHUB_ENV
          # tarball that holds only the docker image
          echo "IMAGE_TAR=${{ env.IMAGE_NAME }}-${{ steps.pkg.outputs.version }}.image.tgz" >> $GITHUB_ENV
          # final install bundle (keeps same naming convention)
          echo "TAR_FILE=${{ env.IMAGE_NAME }}-${{ steps.pkg.outputs.version }}.tgz" >> $GITHUB_ENV
          # directory placed at archive root
          echo "BUNDLE_DIR=polarity-slack-bot" >> $GITHUB_ENV

      # ──────────────────────────────────────────────────────────────
      # 3. Build & save Docker image
      # ──────────────────────────────────────────────────────────────
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Save image to compressed tarball
        run: |
          docker save $IMAGE_NAME:$IMAGE_TAG | gzip > "$IMAGE_TAR"
          # create checksum so update-bot can validate cached copy
          sha256sum "$IMAGE_TAR" > "$IMAGE_TAR.sha256"

      # ──────────────────────────────────────────────────────────────
      # 3a. Build full install bundle (scripts + image)
      # ──────────────────────────────────────────────────────────────
      - name: Create install bundle
        run: |
          mkdir -p "$BUNDLE_DIR/docker-images"
          # copy helper scripts & docs
          cp README.md start-bot.sh stop-bot.sh uninstall-bot.sh update-bot.sh .env.example LICENSE Dockerfile "$BUNDLE_DIR"/
          # move docker image and its checksum into sub-dir
          mv "$IMAGE_TAR" "$IMAGE_TAR.sha256" "$BUNDLE_DIR/docker-images/"
          # pack everything
          tar -czf "$TAR_FILE" "$BUNDLE_DIR"

      # ──────────────────────────────────────────────────────────────
      # 3b. Produce SHA-256 checksum (fallback integrity check)
      # ──────────────────────────────────────────────────────────────
      - name: Generate checksum
        run: sha256sum "$TAR_FILE" > "$TAR_FILE.sha256"

      # ──────────────────────────────────────────────────────────────
      # 3b. Install cosign and sign the tarball (key-less / OIDC)
      # ──────────────────────────────────────────────────────────────
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Sign tarball with cosign (keyless)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign-blob --yes \
            --output-certificate "$TAR_FILE.pem" \
            --output-signature   "$TAR_FILE.sig" \
            "$TAR_FILE"

      # ──────────────────────────────────────────────────────────────
      # 4. Build self-extracting installer
      # ──────────────────────────────────────────────────────────────
      - name: Build self-extracting installer
        run: |
          INSTALLER="polarity-slack-bot-${{ steps.pkg.outputs.version }}.run"
          STUB="scripts/self-extract-stub.sh"

          # Compute SHA-256 of payload tarball
          PAYLOAD_SHA=$(sha256sum "$TAR_FILE" | cut -d' ' -f1)

          # Inject SHA into stub
          sed "s|@@PAYLOAD_SHA256@@|${PAYLOAD_SHA}|" "$STUB" > "$INSTALLER"

          # Embed signature and certificate
          echo "__SIG_BEGIN__" >> "$INSTALLER"
          cat "$TAR_FILE.sig"  >> "$INSTALLER"
          echo "__SIG_END__"   >> "$INSTALLER"
          echo "__CRT_BEGIN__" >> "$INSTALLER"
          cat "$TAR_FILE.pem"  >> "$INSTALLER"
          echo "__CRT_END__"   >> "$INSTALLER"

          # Append payload
          echo "__ARCHIVE_BEGIN__" >> "$INSTALLER"
          cat "$TAR_FILE"          >> "$INSTALLER"
          chmod +x "$INSTALLER"

      # ──────────────────────────────────────────────────────────────
      # 5. Sign installer with cosign (keyless)
      # ──────────────────────────────────────────────────────────────
      - name: Sign installer with cosign (keyless)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          INSTALLER="polarity-slack-bot-${{ steps.pkg.outputs.version }}.run"
          cosign sign-blob --yes \
            --output-certificate "$INSTALLER.pem" \
            --output-signature   "$INSTALLER.sig" \
            "$INSTALLER"

      # ──────────────────────────────────────────────────────────────
      # 6. Create GitHub release and upload assets
      # ──────────────────────────────────────────────────────────────
      - name: Release & upload image
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.pkg.outputs.version }}
          name: "Polarity Slack Bot v${{ steps.pkg.outputs.version }}"
          files: |
            ${{ env.TAR_FILE }}
            ${{ env.TAR_FILE }}.sha256
            ${{ env.TAR_FILE }}.sig
            ${{ env.TAR_FILE }}.pem
            polarity-slack-bot-${{ steps.pkg.outputs.version }}.run
            polarity-slack-bot-${{ steps.pkg.outputs.version }}.run.sig
            polarity-slack-bot-${{ steps.pkg.outputs.version }}.run.pem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
