name: Block merge if version not bumped

on:
  pull_request:
    branches: [main]                       # PRs targeting main
    types: [opened, reopened, synchronize]

jobs:
  ensure-version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0                   # need history to read main’s package.json

      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Compare package.json versions
        run: |
          # version in PR (HEAD)
          HEAD_VERSION=$(node -e "console.log(require('./package.json').version)")

          # fetch main to ensure up-to-date
          git fetch origin main --depth=1

          # version in main (BASE)
          BASE_VERSION=$(git show origin/main:package.json | node -p "JSON.parse(require('fs').readFileSync(0,'utf8')).version")

          echo "HEAD version: $HEAD_VERSION"
          echo "BASE version: $BASE_VERSION"

          if [ "$HEAD_VERSION" = "$BASE_VERSION" ]; then
            echo "::error title=Version unchanged::package.json version ($HEAD_VERSION) must be bumped before merging into main."
            exit 1
          fi
